🔖 可以通过回复消息触发，添加PluginMetaData
A-kirami/nonebot-plugin-answersbook pull request #6
Opened 2023-05-17 11:45 UTC by BiologyHazard

### 这个 PR 带来了什么样的更改？

- [ ] 错误修复
- [x] 新功能 
- [ ] 文档/注释
- [ ] 代码格式
- [x] 代码重构
- [ ] 测试用例
- [ ] 性能优化
- [ ] 外观样式
- [ ] 项目构建
- [ ] 依赖环境
- [ ] 持续集成/部署
- [ ] 其他，请描述:

### 这个 PR 是否存在破坏性变更？

- [ ] 是的，并已在 issue #___ 号中获得批准
- [x] 没有

### 描述

可以通过回复消息触发回答
添加插件元数据

### 动机和背景

### 其他信息

### 检查工作

- [ ] 我对我的代码进行了注释，特别是在难以理解的部分
- [x] 我的更改需要更新文档，并且已对文档进行了相应的更改
- [ ] 我添加了测试并且已经在本地通过，以证明我的修复补丁或新功能有效
- [ ] 我已检查并确保更改没有与其他打开的 [Pull Requests](../pulls) 重复

2023-05-18 12:29 UTC, A-kirami requested changes

2023-05-18 12:29 UTC, A-kirami commented on nonebot_plugin_answersbook/__init__.py
> +look_answer = on_command("翻看答案")
由于 `on_command` 会受命令头影响，改变了原有的触发逻辑，这会让用户无法使用旧指令。

改为或者添加 `on_startswith` 以向后兼容，避免用户付出额外学习成本。

2023-05-18 12:29 UTC, A-kirami commented on nonebot_plugin_answersbook/__init__.py
> +    if event.original_message[0].type == 'reply':
可通过 `event.reply` 判断是否为回复消息
`event.reply` 中包含了回复消息的信息

2023-05-18 14:54 UTC, BiologyHazard commented on nonebot_plugin_answersbook/__init__.py
> +                                      MessageSegment.text(answer)]))
不知道有没有更优雅的回复消息的方式，目前我只知道可以这样，，

2023-05-20 00:27 UTC, A-kirami approved these changes

2023-05-20 13:10 UTC, merged